services:
  - type: web
    name: leaf-diseases-api
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    repo: https://github.com/Aditya-Kumrawat/leaf-diseases-detect
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000  # Match this with the port you run in app.py or main file
