services:
  - type: web
    name: leaf-diseases-api
    env: python
    plan: free
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    repo: https://github.com/YOUR_USERNAME/YOUR_REPO_NAME
    branch: main
    autoDeploy: true
    envVars:
      - key: PORT
        value: 10000  # Match this with the port you run in app.py or main file
